name: chat_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  firebase_storage: ^13.0.0
  image_picker: ^1.2.0
  cloud_firestore: ^6.0.0
  firebase_messaging: ^16.0.0
  permission_handler: ^12.0.1
  firebase_database: ^12.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/chat1.png
    - assets/app_icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  adaptive_icon_background: "#191919"
  adaptive_icon_foreground: "assets/app_icon.png"
